data_root: data
output_dir: submissions
batch_size: 32
num_epochs: 20
patience: 5
learning_rate: 0.001
embedding_dim: 128
margin: 1.0
threshold: 0.5
random_state: 42
num_workers: 0
image_size: [224, 224]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
model_path: submissions/siamese_model.pth
submission_path: submissions/submission_siamese.csv